from rest_framework import serializers
from .models import Task

class TaskSerializer(serializers.Serializer):
    # 1. Read-Only Fields (Generated by the backend/database)
    id = serializers.CharField(read_only=True)
    created_at = serializers.DateTimeField(read_only=True)
    
    # 2. Writable Fields (Data coming from your Desktop App)
    title = serializers.CharField(max_length=200)
    description = serializers.CharField(allow_blank=True, required=False)
    # Made these required=False so the AI can freely overwrite them
    category = serializers.CharField(required=False, allow_blank=True)
    dead_line = serializers.DateTimeField()
    estimated_duration = serializers.FloatField(required=False, default=0.0)
    
    # 3. Status Fields
    is_completed = serializers.BooleanField(default=False)
    
    # --- THE 5-PILLAR NEURO ENGINE METADATA ---
    # These fields catch the AI's math and send it safely to your UI
    cognitive_score = serializers.FloatField(required=False, default=1.0)
    procrastination_risk = serializers.FloatField(required=False, default=1.0)
    reschedule_count = serializers.IntegerField(required=False, default=0)

    # 4. How to Create a Mongo Document
    def create(self, validated_data):
        task = Task(**validated_data)
        task.save()
        return task

    # 5. How to Update a Mongo Document 
    def update(self, instance, validated_data):
        for attr, value in validated_data.items():
            setattr(instance, attr, value)
        instance.save()
        return instance