from rest_framework import serializers
from .models import Task

class TaskSerializer(serializers.Serializer):
    # 1. Read-Only Fields (Generated by the backend/database)
    id = serializers.CharField(read_only=True)
    created_at = serializers.DateTimeField(read_only=True)
    
    # 2. Writable Fields (Data coming from your Desktop App)
    title = serializers.CharField(max_length=200)
    description = serializers.CharField(allow_blank=True, required=False)
    category = serializers.CharField()
    dead_line = serializers.DateTimeField()
    estimated_duration = serializers.FloatField()
    
    # 3. Default Fields
    is_completed = serializers.BooleanField(default=False)
    ai_confidence_score = serializers.FloatField(required=False, default=0.0)

    # 4. How to Create a Mongo Document
    def create(self, validated_data):
        # validated_data automatically includes the 'owner' we stapled in views.py
        task = Task(**validated_data)
        task.save()
        return task

    # 5. How to Update a Mongo Document (for your drag-and-drop timeline)
    def update(self, instance, validated_data):
        for attr, value in validated_data.items():
            setattr(instance, attr, value)
        instance.save()
        return instance